name: gbench
version: $version
summary: Application for viewing and analyzing sequences
description: |
  NCBI Genome Workbench is an integrated application for viewing and analyzing
  sequence data. With Genome Workbench, you can view data in publically available
  sequence databases at NCBI, and mix this data with your own private data.
  Genome Workbench can display sequence data in many ways, including graphical
  sequence views, various alignment views, phylogenetic tree views, and tabular
  views of data. It can also align your private data to data in public databases,
  display your data in the context of public data, and retrieve BLAST results.

icon: ncbilogo.svg

grade: devel
confinement: devmode

parts:
  gbench:
    plugin: dump
    source: gbench-linux-x86_64-$SNAPCRAFT_PROJECT_VERSION-1.tgz
    stage-packages:
      - libc6
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglew1.13
      - libglu1-mesa
      - libice6
      - libsm6
      - libxcomposite1
      - libxcursor1
      - libxi6
      - libxinerama1
      - libxrandr2
      - libatk1.0-0
      - libcairo2
      - libdatrie1
      - libfontconfig1
      - libftgl2
      - libgdk-pixbuf2.0-0
      - libgraphite2-3
      - libharfbuzz0b
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libgtk2.0-0
      - libx11-6
      - libidn2-0
      - libxml2
      - libxslt1.1
      - libunistring0
      - libxcb1
      - libpng16-16
      - zlib1g
      - libstdc++6
      - libgnutls30
      - locales-all
    after: [desktop-gtk2]

apps:
  gbench:
    command: desktop-launch $SNAP/opt/ncbi/gbench-$SNAPCRAFT_PROJECT_VERSION/bin/gbench
    desktop: usr/share/applications/ncbi-gbench.desktop
    plugs: [home, network, x11, wayland, desktop, opengl]
  macroflow:
    command: opt/ncbi/gbench-$SNAPCRAFT_PROJECT_VERSION/bin/macroflow
    plugs: [home, network, x11, wayland, desktop]
  macro:
    command: opt/ncbi/gbench-$SNAPCRAFT_PROJECT_VERSION/bin/gbenchmacro
  demo:
    command: desktop-launch $SNAP/opt/ncbi/gbench-$SNAPCRAFT_PROJECT_VERSION/bin/demo_widgets_gl_wx
    plugs: [home, network, x11, wayland, desktop, opengl]
