# $Id: Makefile.cleanup-blastdb-volumes 590894 2019-08-07 14:59:53Z camacho $
##################################

include $(builddir)/Makefile.mk

SCRIPT_NAME = cleanup-blastdb-volumes.py

all:
	@if [ '$(BINCOPY)' != '@:' -a -d $(bindir) -a -w $(bindir) -a $(srcdir) != . ]; then \
	        echo $(BINCOPY) $(srcdir)/$(SCRIPT_NAME) $(bindir) && \
	        $(BINCOPY) $(srcdir)/$(SCRIPT_NAME) $(bindir) || exit $? ; \
	fi

purge:
	-$(RM) $(bindir)/$(SCRIPT_NAME)

clean:

