# $Id: Makefile.ncbi_xloader_genbank.mk 590906 2019-08-07 16:22:38Z vakatov $

GENBANK_THIRD_PARTY_LIBS        = $(PSG_CLIENT_LIBS)
GENBANK_THIRD_PARTY_STATIC_LIBS = $(PSG_CLIENT_STATIC_LIBS)
GENBANK_PSG_CLIENT_LIB          = psg_client
GENBANK_PSG_CLIENT_LDEP         = $(GENBANK_PSG_CLIENT_LIB) xconnserv

REQUIRES = PSGLoader
