Seq-submit ::= {
  sub {
    contact {
      contact {
        name name {
          last "Gryzenhout",
          first "Marieka",
          initials "M.M."
        },
        affil std {
          affil "Forestry and Agricultural Biotechnology Institute (FABI)",
          city "Pretoria",
          sub "Gauteng",
          country "South Africa",
          street "University of Pretoria",
          email "Marieka.Gryzenhout@fabi.up.ac.za",
          fax "+27-12-4203938",
          phone "+27-12-4203933",
          postal-code "0002"
        }
      }
    },
    cit {
      authors {
        names std {
          {
            name name {
              last "Gryzenhout",
              first "Marieka",
              initials "M."
            }
          },
          {
            name name {
              last "Vermeulen",
              first "Marcele",
              initials "M."
            }
          },
          {
            name name {
              last "Dick",
              first "Margaret",
              initials "M."
            }
          },
          {
            name name {
              last "Wingfield",
              first "Michael",
              initials "M.J."
            }
          }
        },
        affil std {
          affil "Forestry and Agricultural Biotechnology Institute (FABI)",
          city "Pretoria",
          sub "Gauteng",
          country "South Africa",
          street "University of Pretoria",
          postal-code "0002"
        }
      },
      date std {
        year 2009,
        month 8,
        day 5
      }
    },
    hup TRUE,
    reldate std {
      year 2010,
      month 7,
      day 31
    },
    subtype new,
    tool "Sequin 9.20 - MS WINDOWS VISTA"
  },
  data entrys {
    set {
      class nuc-prot,
      descr {
        source {
          genome genomic,
          org {
            taxname "Falco cherrug",
            common "Saker falcon",
            db {
              {
                db "taxon",
                tag id 345164
              }
            },
            orgname {
              gcode 1,
              mgcode 2,
              div "VRT"
            }
          }
        }
      },
      seq-set {
        seq {
          id {
            local str "CMW8541SA"
          },
          descr {
            title "Holocryphia eucalypti",
            molinfo {
              biomol genomic
            },
            user {
              type str "OriginalID",
              data {
                {
                  label str "LocalId",
                  data str "CMW8541SA"
                }
              }
            }
          },
          inst {
            repr raw,
            mol dna,
            length 987,
            seq-data ncbi4na '211122182824442414212442282412142118442484818481
221212218122281212442442221242114184412424428244428882284281122122242481428121
124421228224142822142824142421841124828128821124144818482884824428412214422822
142218218228422822842282282288221824441288284844228412241428842228828412424888
282482214422822442112114818488222242422482282482418282414222448122184418422482
242422442222882442214284882248222412112882482882442214822FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
F84122142248442422212822882242422282122484222414884122214211184882412222114112
184184428422824412882242112442242812284124842828422182884812488888482882828482
821212182824418221228282444288488888428112228428882282828222281214224844211448
282218411441448241441221418424211248221414211411282482281288248241484418222211
211248221412242228284282218222222211444228211418482282212288848244211282212242
218221441428288211424848844241421488212242218488224424211442888288421884481212
8440'H
          }
        },
        seq {
          id {
            local str "CMW8541SA_1"
          },
          descr {
            title "unnamed protein product [Falco cherrug]",
            molinfo {
              biomol peptide,
              tech concept-trans-a
            },
            user {
              type str "OriginalID",
              data {
                {
                  label str "LocalId",
                  data str "CMW8541SA_1"
                }
              }
            }
          },
          inst {
            repr raw,
            mol aa,
            length 235,
            seq-data ncbieaa "-TISGEHGLDSNGVYNGTSELQLERMNVYFNEASGNKYVPRAVLVDLE
PGTMDAVRAGPFGQLFRPDNFVFGQSXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTSRGAHSFRALTVPELTQ
QMFDPKNMMAASDFRNGRYLTCSAIFRGKVSMKEVEDQMRNVQSKNSSYFVEWIPNNVQTALCSIPPKGLKMSSTFVG
NSTAIQELFKRVGEQFTAMFRRKAFLHWYTG"
          }
        }
      },
      annot {
        {
          data ftable {
            {
              data cdregion {
                code {
                  id 1
                }
              },
              product whole local str "CMW8541SA_1",
              location mix {
                int {
                  from 0,
                  to 40,
                  strand plus,
                  id local str "CMW8541SA"
                },
                int {
                  from 121,
                  to 175,
                  strand plus,
                  id local str "CMW8541SA"
                },
                int {
                  from 291,
                  to 649,
                  strand plus,
                  id local str "CMW8541SA"
                },
                int {
                  from 738,
                  to 986,
                  strand plus,
                  id local str "CMW8541SA"
                }
              }
            }
          }
        }
      }
    }
  }
}
