Seq-entry ::= set {
  class genbank,
  seq-set {
    set {
      class nuc-prot,
      descr {
        source {
          genome genomic,
          org {
            taxname "Methanobacterium formicicum phage",
            orgname {
              gcode 1
            }
          }
        }
      },
      seq-set {
        seq {
          id {
            local str "Seq2",
            genbank {
              accession "KF591394"
            }
          },
          descr {
            molinfo {
              biomol genomic,
              completeness partial
            },
            user {
              type str "OriginalID",
              data {
                {
                  label str "LocalId",
                  data str "Seq2"
                },
                {
                  label str "GenBank",
                  data str "gb|KF591394|"
                }
              }
            }
          },
          inst {
            repr raw,
            mol dna,
            length 207,
            strand ds,
            seq-data iupacna "GATGCGTTCAAAAGGGGATGAAGCAAAAGAGATAGAGAAATTTCCTGA
AGACGGATGAGGGGAGCATGGCAGCGTTCTGCTACATTGCAACTTTCATTACATTGTTAGCGGACCTGATCAGTGGAA
ATATCACGTTCACTGAGTTCATGAGTGAGATGTGGGTGGCTTTTCAGCAACTAATCGGTGAAGTCATATGGGTCATTA
ACA"
          },
          annot {
            {
              data ftable {
                {
                  data gene {
                    locus "Hypothetical protein gene",
                    desc "Hypothetical protein gene"
                  },
                  partial TRUE,
                  location int {
                    from 10,
                    to 57,
                    strand plus,
                    id genbank {
                      accession "KF591394"
                    },
                    fuzz-from lim lt,
                    fuzz-to lim gt
                  }
                },
                {
                  data gene {
                    locus "putative tape measure protein gene",
                    desc "tape measure protein gene"
                  },
                  partial TRUE,
                  location int {
                    from 65,
                    to 206,
                    strand plus,
                    id genbank {
                      accession "KF591394"
                    },
                    fuzz-from lim lt,
                    fuzz-to lim gt
                  }
                }
              }
            }
          }
        },
        seq {
          id {
            local str "Seq2_prot_2",
            general {
              db "TMSMART",
              tag id 39787266
            }
          },
          descr {
            molinfo {
              biomol peptide,
              completeness no-ends
            },
            user {
              type str "OriginalID",
              data {
                {
                  label str "LocalId",
                  data str "Seq2_prot_2"
                },
                {
                  label str "General",
                  data str "gnl|TMSMART|39787266"
                }
              }
            }
          },
          inst {
            repr raw,
            mol aa,
            length 15,
            seq-data ncbieaa "KGDEAKEIEKFPEDG"
          },
          annot {
            {
              data ftable {
                {
                  data prot {
                    name {
                      "Hypothetical protein"
                    }
                  },
                  partial TRUE,
                  location int {
                    from 0,
                    to 14,
                    id local str "Seq2_prot_2",
                    fuzz-from lim lt,
                    fuzz-to lim gt
                  }
                }
              }
            }
          }
        },
        seq {
          id {
            local str "Seq2_prot_3",
            general {
              db "TMSMART",
              tag id 39787267
            }
          },
          descr {
            molinfo {
              biomol peptide,
              completeness no-right
            },
            user {
              type str "OriginalID",
              data {
                {
                  label str "LocalId",
                  data str "Seq2_prot_3"
                },
                {
                  label str "General",
                  data str "gnl|TMSMART|39787267"
                }
              }
            }
          },
          inst {
            repr raw,
            mol aa,
            length 45,
            seq-data iupacaa "MAAFCYIATFITLLADLISGNITFTEFMSEMWVAFQQLIGEVIWV"
          },
          annot {
            {
              data ftable {
                {
                  data prot {
                    name {
                      "putative tape measure protein"
                    },
                    desc "tape measure protein"
                  },
                  partial TRUE,
                  location int {
                    from 0,
                    to 44,
                    id local str "Seq2_prot_3",
                    fuzz-to lim gt
                  }
                }
              }
            }
          }
        }
      },
      annot {
        {
          data ftable {
            {
              data cdregion {
                frame one,
                code {
                  id 1
                }
              },
              partial TRUE,
              product whole local str "Seq2_prot_2",
              location int {
                from 10,
                to 57,
                strand plus,
                id genbank {
                  accession "KF591394"
                },
                fuzz-from lim lt,
                fuzz-to lim gt
              }
            },
            {
              data cdregion {
                frame one,
                code {
                  id 1
                }
              },
              partial TRUE,
              comment "[intronless gene]",
              product whole local str "Seq2_prot_3",
              location int {
                from 65,
                to 200,
                strand plus,
                id local str "Seq2",
                fuzz-to lim gt
              }
            }
          }
        }
      }
    }
  }
}
