Seq-entry ::= set {
  class genbank,
  seq-set {
    seq {
      id {
        local str "Seq1",
        general {
          db "BankIt",
          tag str "1657039/Seq1"
        },
        general {
          db "TMSMART",
          tag id 39787263
        },
        genbank {
          accession "KF591393"
        }
      },
      descr {
        molinfo {
          biomol genomic,
          completeness partial
        },
        source {
          genome genomic,
          org {
            taxname "Gadus morhua",
            common "Atlantic cod",
            db {
              {
                db "taxon",
                tag id 8049
              }
            },
            orgname {
              gcode 1,
              mgcode 2,
              div "VRT"
            }
          }
        },
        update-date std {
          year 2013,
          month 8,
          day 27,
          hour 10,
          minute 59,
          second 58
        }
      },
      inst {
        repr raw,
        mol dna,
        length 141,
        strand ds,
        seq-data iupacna "TAAAACAGCTCAGGGCGAGGCGGCTACTATCACTAAAAATGATCATAGAGTG
GAAGGGTTGGATAAATCTATTTTAAACCCTGATTTAATGCAGGCTGAGATCGATTATGCTCTTAAATTGATTGAAGCT
AAGGAATGACC"
      },
      annot {
        {
          data ftable {
            {
              data rna {
                type mRNA,
                ext name "some new mRNA"
              },
              product whole other {
                accession "NM_206956",
                version 2
              },
              location int {
                from 0,
                to 140,
                strand plus,
                id genbank {
                  accession "KF591393"
                }
              }
            },
            {
              data imp {
                key "D-loop"
              },
              location int {
                from 0,
                to 140,
                strand plus,
                id genbank {
                  accession "KF591393"
                }
              },
              qual {
                {
                  qual "allele",
                  val "ddd"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        local str "Seq2",
        general {
          db "BankIt",
          tag str "1657039/Seq2"
        },
        general {
          db "TMSMART",
          tag id 39787265
        },
        genbank {
          accession "KF591394"
        }
      },
      descr {
        source {
          genome genomic,
          org {
            taxname "Fenneropenaeus chinensis",
            db {
              {
                db "taxon",
                tag id 139456
              }
            },
            orgname {
              gcode 1,
              mgcode 5,
              div "INV"
            }
          }
        },
        update-date std {
          year 2013,
          month 8,
          day 27,
          hour 10,
          minute 59,
          second 58
        }
      },
      inst {
        repr raw,
        mol dna,
        length 128,
        strand ds,
        seq-data iupacna "CCGGGGGGTATTGACATGCTTATTGAGCCTGTTGGGCTTTGCAATTGGGCAA
TTCATCAGTTTCAGCATGTCCCTCCTACTCCTCATATACGATCTTGGAGTGCAACTGATAACATGGGTCATTAACA"
      },
      annot {
        {
          data ftable {
            {
              data imp {
                key "D-loop"
              },
              location int {
                from 0,
                to 127,
                strand plus,
                id genbank {
                  accession "KF591394"
                }
              },
              qual {
                {
                  qual "allele",
                  val "dom"
                }
              }
            }
          }
        }
      }
    }
  }
}
