Seq-submit ::= {
  sub {
    contact {
      contact {
        name name {
          last "Al-Hassan",
          first "Leena",
          middle "",
          initials "L.",
          title ""
        },
        affil std {
          affil "Brighton and Sussex Medical School",
          div "Global Health and Infection",
          city "Brighton",
          country "United Kingdom",
          street "University of Sussex",
          email "l.al-hassan@bsms.ac.uk",
          postal-code "BN1 9PX"
        }
      }
    },
    cit {
      authors {
        names std {
          {
            name name {
              last "Al-Hassan",
              first "Leena",
              initials "L."
            }
          }
        },
        affil std {
          affil "Brighton and Sussex Medical School",
          div "Global Health and Infection",
          city "Brighton",
          country "United Kingdom",
          street "University of Sussex",
          postal-code "BN1 9PX"
        }
      },
      date std {
        year 2020,
        month 4,
        day 28
      }
    },
    hup FALSE,
    subtype new,
    tool "table2asn 1.24.69",
    comment "SUB7330260"
  },
  data entrys {
    seq {
      id {
        local id 83
      },
      descr {
        source {
          org {
            taxname "Vibrio parahaemolyticus",
            db {
              {
                db "taxon",
                tag id 670
              }
            },
            orgname {
              attrib "specified",
              lineage "Bacteria; Proteobacteria; Gammaproteobacteria;
 Vibrionales; Vibrionaceae; Vibrio",
              gcode 11,
              mgcode 0,
              div "BCT"
            }
          }
        },
        molinfo {
          biomol genomic
        },
        create-date std {
          year 2020,
          month 4,
          day 28
        },
        update-date std {
          year 2020,
          month 4,
          day 28
        }
      },
      inst {
        repr delta,
        mol dna,
        length 3439,
        ext delta {
          literal {
            length 20,
            seq-data iupacna "AAAAATACTATNAANACTTT"
          },
          literal {
            length 3169,
            seq-data iupacna "GTTCAAGCGTACCTACTCTCGACTCTGCCCAGCTTTCTGGTAAATATT
TTAAATTTTTATAAATACTGTTTTGGTTTTCAAGATCTTCTAAAGAATTATAAGAGCTAGACTGGTAATGAGGAGTTT
TATAGTTACCAGCATTACGATATAACCCTTCTGCCCGTAAAGCTACATGTGGGCTTAAGCCAACTGTTACACCTGCTG
TGGTCAACTTCTCATTACTGCCAGTATTAAAACGTAATGTAGTATTACCCTCTAATCCGTCTTGAGGCATTTGGGTTG
GAATTTTATAGTCAATGACATTGACTACCCCTGCCGCACTATTTGAACTATACAAAAGGGTACTTGCACCACGTATAA
TTTCAATAGACTTAGCTAAACTTGGTTCAACTGTGACAGCGTGATCTGGGGACATATTAGACATATCCAACACGTCAG
CATTATTCTGTAAAACTTTAATACGTTTTCCTTCCTGCCCACGAATAATAGGAGTAGATGCTCCACCTCCATATTGAT
TAGAATGAATTCCTAATTCCGTACCCAAGGCATCCCCTAGAGTTGTCGAACGCTGTTTAAGTTTACTAGTATCAATAA
ACTGATTACTAACATTTAGACTTTTGCCTAACAGCTCAGACCCTAACTCATCAGATTGTGCAGTTAATACTATTGTAT
TTAAGGTAGTAACAGGCCCTTCAGCTGCCAATAAAATTTTCGAGGCCCCTAAAGTAATTAAAGCTAAAAATAGTTTAC
TTTTATTTAGCATAAAACAACCAAATTTAATGTTATATTATAATATAACACTTAAAAATTTATAAAATCTACTATTTA
AATTTTTGAATGGTAATCCCCCCTAAAAATGAAGTCAAAAATGGGAGCCTAAGCTCCCATTCTTATTGATGATTTTTT
AATTCTTTTAGCATAGCATCTCGTAAAATTTCATTCATACGTGTTTGATAACCTTTGCCTTGTGCTTTGAACCAAGCA
AGTACATCAGCATCTAACCGAATTGAAGTTTGTTGCTTTACTGGGCGGTAAAATTGATTTTGGCGTACAGCATTGCTC
CAGTCTGTAATTTCAGGAATATCTGATAGATCTAGCTGATCATCAGGAACCGTGCCTTTAGCAAGCAAGCGTTGAATT
TCAGCATCTTGCTTCTCACCAAATTTCTCATTCAGCTCTTTGTGTGAGTATCTAACCATGCTCATATTTGTTTCGCTC
CGCTTTAGTGACTTGCCTTGCACTAATGATTCGGATGATTTCACAGTCATCTTCATCAAAAATGGTGTGAGCCACCAA
TAACATTAGTACGCCTTTAACTCGTCCAATGGTTTGCCAACGTTCTTCACCATTGGTATGTCTGTCTTGGATTGAGAT
CCGTAATGGATCTTCAAAAACAAGGCTTGCAGTTTCGAAAGAGATATCATGCTTTTTCTGATTCTTTCGATTCTTAGC
CTCATCCCATTCAAAATACTGTTCCATAAAAAACATTCAAATTTGTATATACAATAATGTATCACAAAATTGTATCAC
TCAACCAGATTCGTGTAATTTTTAGTCAAAATTATTGGCAAGAAGTATCAAAACTGCTCATAAAAAAGCCGACTTGTT
TCAAAGTCGGCTTTTTGGGCATGAGATGGTGCAAATATTAAGTCTACAGTTGCTTCATTGTCGTTATAAGCAATTTGA
GATACCCAACGACTCATAACATTTCGGATATTCCCATTAGCTTTTTTCTCTTGATAGCTAAATTGACGCGCGAATAAA
TCCTTACAAGCATCTTTTAAGGCTTGATAAGCTGTATTACGGTGTACACCAAATTGATTGATATAACTATCTGCATGA
ACTTCTAATGGATCATTTGCATTAATCCCTTTCCCACTTTCCCTTGCTTCAACAATAGCCAATAAAATTAAACGTTGT
TCTACTAAGTCTAAGTTATAGCTTGCGTTGATTAAGGCATTGTCCTTTACAACTAAATCTCTCATAGCCACTATTTTT
TATTGTGTATAAGTACACGTTAATATTATTTGTGTACTAATGCAAGGTAAACGTGGACATATTGCAAGGTAAACGTGG
ACATATTGCAAGGTAAACGTGGACATATTGCAAGGTAAACGTGGACATATAAGAGCTAAAACCCTTTATTCATAAGGC
TTTCAAGCCATTTAAAAGTATTTAAAAACTTTAAAATAATTAAAAGCCCAGGGAATGAAAAATTGCCCTTGGTTTTCG
CTTCGCTCAAACTCTATTGAACTTCGCTTTCGCTCAGTTCGTTGGGGCAATTTTTTGGTTAATACTGGCGTGACTTTA
AAAAAAAGCAAAAGAAACTTGGAATTCGCTTCGCTCATAAAACTTTTTTACTCGCTACGCTCGATCCAGGAGCAAATT
TCTGCACGAAACTTACGCTTTCTTAGGCTAAAGAGGACAAAAAAATGTTTTTCAGAGGGTCTAGGCGCAAATTTTGAT
AGTTCGCTCGTAGACACTCGCTCTATGCATCTATCTAAAGTCAAAATACCTCTTTATTTCGCTCTCATTTGCGTTTTT
TGAGCTGTTTTGTGTTTTTCACTATGAGATCTATGTTTTCTAGGTAAAGGCTCTTAAATCGCATTTGAACGCGTTCTA
TGAAGCTTTTCATAATTAAAGTTTTGGGTTGAAATTTTTAACCTGGATGAATGGACAAAAAATTGATTTTTTACGTTT
TTCTAAACAAGGAAATAAATACTTTTTTCCATGCAAAACCAAGCACCGGCCCTACGTCACTTTAGCCAATTTTCCAAT
CCAAGATCCGGCACATGCCGGGATTTTTTTGTCACACACCACGCATCTAACGATGACACCCCTCAAAGCCTTACAGGA
TAAGGATTTCAGCGATTTTTTAGGGTCTCAGAAACGTGTACAGAAAAATGGTCTTTTTTTAGAATAAGTGATTGAATT
ATCTATTTTTTATGCTGTGCTCATGGTTGTACATCAAAACAACACTTTTTTTAGATAAGATATTGATAAATTTAAGAA
AAAATATGTACTCATGATTGTACATAAAAAAAGCATTATATTTAAATAAGTTTTTGTTTTAGAATAAATTAATTCTGT
ACAAATAAGTTTGTACGTAATCTAATTATTATTTTTTATTTAATTAGTTGAATTATATATATTTAATTTTGTACAAAAT"
          },
          literal {
            length 178,
            seq-data iupacna "NTANNTNTAATAANANNTNTANTTTANNNGNNAAANAGTNAAAANNTA
TNNNNNNAGNTTNGATNNANAANTAGNANAATNNNANNANNNATTNNNTNNTNNANAANGAATNANAANNAGTAAANN
ATTNAGNNAANNTTTNNCNANNNNTNTTNNNTNTNTNNNNNTTNNANNNNAA"
          },
          literal {
            length 25,
            seq-data gap {
              type scaffold,
              linkage linked,
              linkage-evidence {
                {
                  type paired-ends
                }
              }
            }
          },
          literal {
            length 2,
            seq-data iupacna "AT"
          },
          literal {
            length 40,
            seq-data gap {
              type scaffold,
              linkage linked,
              linkage-evidence {
                {
                  type paired-ends
                }
              }
            }
          },
          literal {
            length 5,
            seq-data iupacna "ANNNN"
          }
        }
      }
    }
  }
}
