Seq-entry ::= set {
  class pop-set,
  seq-set {
    set {
      class nuc-prot,
      descr {
        source {
          genome genomic,
          origin natural,
          org {
            taxname "Nyssomyia umbratilis",
            db {
              {
                db "taxon",
                tag id 182988
              }
            },
            syn {
              "Lutzomyia (Nyssomyia) umbratilis",
              "Lutzomyia umbratilis"
            },
            orgname {
              name binomial {
                genus "Nyssomyia",
                species "umbratilis"
              },
              mod {
                {
                  subtype old-name,
                  subname "Lutzomyia umbratilis"
                }
              },
              lineage "Eukaryota; Metazoa; Ecdysozoa; Arthropoda; Hexapoda;
 Insecta; Pterygota; Neoptera; Endopterygota; Diptera; Nematocera;
 Psychodoidea; Psychodidae; Nyssomyia",
              gcode 1,
              mgcode 5,
              div "INV"
            }
          }
        }
      },
      seq-set {
        seq {
          id {
            local str "FMAN01",
            general {
              db "NCBIFILE",
              tag str "submission sequence.sqn/FMAN01"
            },
            general {
              db "TMSMART",
              tag id 58028517
            },
            genbank {
              accession "KT722623"
            }
          },
          descr {
            molinfo {
              tech standard,
              completeness partial
            },
            user {
              type str "OriginalID",
              data {
                {
                  label str "LocalId",
                  data str "FMAN01"
                },
                {
                  label str "General",
                  data str "gnl|NCBIFILE|submission sequence.sqn/FMAN01"
                },
                {
                  label str "General",
                  data str "gnl|TMSMART|58028517"
                },
                {
                  label str "GenBank",
                  data str "gb|KT722623|"
                }
              }
            }
          },
          inst {
            repr raw,
            mol dna,
            length 484,
            strand ds,
            seq-data ncbi2na 'C48FDFBD30E9A733C47601E0EB527FBC35BAD8A41E8BFBCF
A334D8B9C62B00340F1E007C492021F0C6CF8FF2B5350D742FFE49C6BC3492FD58213CD2E39420
034A008FF39F9F1A252ED028CF8C4B82490BF5008E5F93E937FCE805F8E8E0B076178DF09C87C5
D28048BC10CDE2223D6E39EAE03375914E3C71'H
          },
          annot {
            {
              data ftable {
                {
                  data rna {
                    type mRNA,
                    ext name "mRNA product 67name"
                  },
                  partial TRUE,
                  comment "some mRNA comment",
                  location int {
                    from 0,
                    to 117,
                    strand plus,
                    id genbank {
                      accession "KT722623"
                    },
                    fuzz-from lim lt,
                    fuzz-to lim gt
                  }
                },
                {
                  data gene {
                    locus "some gene locus",
                    locus-tag "some gene 89locustag"
                  },
                  location int {
                    from 199,
                    to 483,
                    strand plus,
                    id genbank {
                      accession "KT722623"
                    }
                  }
                },
                {
                  data rna {
                    type premsg,
                    ext name "some 56preRNA"
                  },
                  location int {
                    from 259,
                    to 483,
                    strand plus,
                    id genbank {
                      accession "KT722623"
                    }
                  }
                },
                {
                  data rna {
                    type premsg,
                    ext name "some other preRNA"
                  },
                  location int {
                    from 299,
                    to 483,
                    strand plus,
                    id genbank {
                      accession "KT722623"
                    }
                  }
                }
              }
            }
          }
        },
        seq {
          id {
            local str "FMAN01_1",
            general {
              db "NCBIFILE",
              tag str "submission sequence.sqn/FMAN01_1"
            },
            general {
              db "TMSMART",
              tag id 58028518
            }
          },
          descr {
            title "Per gene product, partial [Nyssomyia umbratilis]",
            molinfo {
              biomol peptide,
              tech concept-trans-a,
              completeness no-ends
            },
            user {
              type str "OriginalID",
              data {
                {
                  label str "LocalId",
                  data str "FMAN01_1"
                },
                {
                  label str "General",
                  data str "gnl|NCBIFILE|submission sequence.sqn/FMAN01_1"
                },
                {
                  label str "General",
                  data str "gnl|TMSMART|58028518"
                }
              }
            }
          },
          inst {
            repr raw,
            mol aa,
            length 39,
            seq-data ncbieaa "YRFLVHNGGYITLETEWSSFVNPWSRQLEFVIGYHRVLR"
          },
          annot {
            {
              data ftable {
                {
                  data prot {
                  },
                  partial TRUE,
                  location int {
                    from 0,
                    to 141,
                    id local str "FMAN01_1",
                    fuzz-from lim lt,
                    fuzz-to lim gt
                  }
                }
              }
            }
          }
        }
      },
      annot {
        {
          data ftable {
            {
              data cdregion {
                frame one,
                code {
                  id 1
                }
              },
              partial TRUE,
              comment "testing comment1",
              product whole local str "FMAN01_1",
              location int {
                from 0,
                to 117,
                strand plus,
                id genbank {
                  accession "KT722623"
                },
                fuzz-from lim lt,
                fuzz-to lim gt
              }
            }
          }
        }
      }
    }
  }
}
