Seq-entry ::= set {
  class genbank,
  seq-set {
    set {
      class phy-set,
      descr {
        title "Botryosphaeriaceae beta-tubulin gene, partial cds."
      },
      seq-set {
        set {
          class nuc-prot,
          descr {
            source {
              genome genomic,
              org {
                taxname "Neofusicoccum occulatum",
                db {
                  {
                    db "taxon",
                    tag id 1167695
                  }
                },
                orgname {
                  name binomial {
                    genus "Neofusicoccum",
                    species "occulatum"
                  },
                  attrib "specified",
                  lineage "Eukaryota; Fungi; Dikarya; Ascomycota;
 Pezizomycotina; Dothideomycetes; Dothideomycetes incertae sedis;
 Botryosphaeriales; Botryosphaeriaceae; Neofusicoccum",
                  gcode 1,
                  mgcode 4,
                  div "PLN"
                }
              }
            }
          },
          seq-set {
            seq {
              id {
                local str "CMW48023"
              },
              descr {
                title "Neofusicoccum occulatum beta-tubulin gene, partial cds.",
                molinfo {
                  biomol genomic
                }
              },
              inst {
                repr raw,
                mol dna,
                length 349,
                strand ds,
                seq-data iupacna "GCAGACCATTTCCGGCGAGCACGGCCTGGACGGCTCTGGTGTGT
GAGTCTGCGCCGTTTCCCGCGCGAATGGCAATGGCTGACCCGCAGCAGCTACAATGGCACCTCCGACCTGCAGCTCGA
GCGCATGAACGTCTACTTCAACGAGGTACTCTCTCACTAATTGCACAAACACGTAAAGTATGGCAATCTTCTGAACGC
GCAGCAGGCGTCCAACAACAAGTACGTTCCTCGTGCCGTCCTCGTCGACCTCGAGCCCGGCACCATGGATGCCGTCCG
CGCCGGCCCCTTCGGCCAGCTCTTCCGCCCCGACAACTTCGTCTTCGGCCAGTCTGGCGCCGGTAACAACT"
              },
              annot {
                {
                  data ftable {
                    {
                      data rna {
                        type mRNA,
                        ext name "beta-tubulin"
                      },
                      partial TRUE,
                      location packed-int {
                        {
                          from 1,
                          to 41,
                          strand plus,
                          id local str "CMW48023",
                          fuzz-from lim lt
                        },
                        {
                          from 92,
                          to 146,
                          strand plus,
                          id local str "CMW48023"
                        },
                        {
                          from 207,
                          to 348,
                          strand plus,
                          id local str "CMW48023",
                          fuzz-to lim gt
                        }
                      }
                    }
                  }
                }
              }
            },
            seq {
              id {
                local str "CMW48023_prot_11",
                general {
                  db "TMSMART",
                  tag id 94361431
                }
              },
              descr {
                title "beta-tubulin, partial [Neofusicoccum occulatum]",
                molinfo {
                  biomol peptide,
                  completeness no-ends
                }
              },
              inst {
                repr raw,
                mol aa,
                length 79,
                seq-data ncbieaa "QTISGEHGLDGSGVYNGTSDLQLERMNVYFNEASNNKYVPRAVL
VDLEPGTMDAVRAGPFGQLFRPDNFVFGQSGAGNN"
              },
              annot {
                {
                  data ftable {
                    {
                      data prot {
                        name {
                          "beta-tubulin"
                        }
                      },
                      partial TRUE,
                      location int {
                        from 0,
                        to 78,
                        id local str "CMW48023_prot_11",
                        fuzz-from lim lt,
                        fuzz-to lim gt
                      }
                    }
                  }
                }
              }
            }
          },
          annot {
            {
              data ftable {
                {
                  data cdregion {
                    code {
                      id 1
                    }
                  },
                  partial TRUE,
                  product whole local str "CMW48023_prot_11",
                  location packed-int {
                    {
                      from 1,
                      to 41,
                      strand plus,
                      id local str "CMW48023",
                      fuzz-from lim lt
                    },
                    {
                      from 92,
                      to 146,
                      strand plus,
                      id local str "CMW48023"
                    },
                    {
                      from 207,
                      to 348,
                      strand plus,
                      id local str "CMW48023",
                      fuzz-to lim gt
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
